name: Documentation
description: Update or add documentation
title: "[DOCS]: "
labels:
  - documentation
  - needs-triage
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill this out!
  - type: textarea
    id: describe-need
    attributes:
      label: Describe the need
      description: What do you wish was different about our docs?
      placeholder: Describe the need for documentation updates here.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Do these docs apply to a specific version?
      placeholder: gh-copilot v0.5.2-beta
    validations:
      required: false
  - type: textarea
    id: output
    attributes:
      label: Relevant terminal output
      description: |
        Please copy and paste any relevant terminal output. This will be automatically formatted into code, so no need for backticks.
        Please check your output before submission to ensure sensitive information is redacted.
      render: bash
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
